# Constants
# File Paths
RAW_DEEPFAKES = './Data/Raw/DF/'
RAW_REAL = './Data/Raw/REAL/'
RAW_TEST = './Data/Raw/TEST/'

TRAIN_DEEPFAKES = './Data/Train/DF/'
TRAIN_REAL = './Data/Train/REAL/'

TEST_DEEPFAKES = './Data/Test/DF/'
TEST_REAL = './Data/Test/Real/'

TRAIN_FPS_DEEPFAKES = './Data/Raw/DF/FPS/'
TRAIN_FPS_REAL = './Data/Raw/REAL/FPS/'

TEST_FPS_DEEPFAKES = './Data/Test/DF/FPS/'
TEST_FPS_REAL = './Data/Test/Real/FPS/'

TRAIN_SEPARATED_DF_FACES = './Data/Train/DF/SEP/'
TRAIN_SEPARATED_REAL_FACES = './Data/Train/REAL/SEP/'

TEST_SEPARATED_DF_FACES = './Data/Test/DF/SEP/'
TEST_SEPARATED_REAL_FACES = './Data/Test/REAL/SEP/'

TRAIN_MV_DF_FACES = '/run/media/u1856817/KINGSTON/MV_DF/'
TRAIN_MV_REAL_FACES = '/run/media/u1856817/KINGSTON/MV_REAL/'

TEST_MV_DF_FACES = '/run/media/u1856817/KINGSTON/MV_DF/'
TEST_MV_REAL_FACES = '/run/media/u1856817/KINGSTON/MV_REAL/'

SAVED_MODELS = '/run/media/u1856817/KINGSTON/Saved_Models/'
