# Constants
# File Paths
RAW_DEEPFAKES = '/run/media/u1856817/KINGSTON/DF_RAW/'
RAW_REAL = '/run/media/u1856817/KINGSTON/REAL_RAW/'
# RAW_TEST = './Data/Raw/TEST/'

TRAIN_DEEPFAKES = '/run/media/u1856817/KINGSTON/DF_CLIPS/'
TRAIN_REAL = '/run/media/u1856817/KINGSTON/REAL_CLIPS/'

# TEST_DEEPFAKES = './Data/Test/DF/'
# TEST_REAL = './Data/Test/Real/'

TRAIN_FPS_DEEPFAKES = '/run/media/u1856817/KINGSTON/DF_RAW/FPS/'
TRAIN_FPS_REAL = '/run/media/u1856817/KINGSTON/REAL_RAW/FPS/'

# TEST_FPS_DEEPFAKES = '/run/media/u1856817/KINGSTON/DF_DATA/FPS/'
# TEST_FPS_REAL = '/run/media/u1856817/KINGSTON/REAL_DATA/FPS/'

TRAIN_SEPARATED_DF_FACES = '/run/media/u1856817/KINGSTON/DF_SEP/'
TRAIN_SEPARATED_REAL_FACES = '/run/media/u1856817/KINGSTON/REAL_SEP/'

TEST_SEPARATED_DF_FACES = './Data/Test/DF/SEP/'
TEST_SEPARATED_REAL_FACES = './Data/Test/REAL/SEP/'

TRAIN_MV_DF_FACES = '/run/media/u1856817/KINGSTON/MV_DF/'
TRAIN_MV_REAL_FACES = '/run/media/u1856817/KINGSTON/MV_REAL/'

SAVED_MODELS = '/run/media/u1856817/KINGSTON/Saved_Models/'
